# Generated by Django 5.0.3 on 2024-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumni_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('enrolment_no', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('lib_barcode', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Alumni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year', models.TextField()),
                ('duration', models.CharField(max_length=1)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_abbr', models.CharField(blank=True, max_length=7, null=True)),
                ('is_active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('div_id', models.AutoField(primary_key=True, serialize=False)),
                ('div_name', models.CharField(max_length=1)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('guard_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('working_gate', models.CharField(max_length=1)),
                ('created_on', models.DateTimeField()),
                ('update_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Guard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('program_abbr', models.CharField(blank=True, max_length=7, null=True)),
                ('is_active', models.CharField(max_length=1)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=2)),
                ('picture', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('is_admin', models.CharField(max_length=1)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolment_no', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('isactive', models.CharField(db_column='isActive', max_length=1)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('lib_barcode', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
