# Generated by Django 5.0.3 on 2024-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('isapproved', models.CharField(db_column='isApproved', default='N', max_length=1)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discussion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocMaster',
            fields=[
                ('docm_id', models.AutoField(db_column='docM_id', primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=255)),
                ('isoffered', models.CharField(db_column='isOffered', max_length=1)),
                ('offeredto', models.CharField(db_column='offeredTo', max_length=1)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocRequest',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField()),
                ('requester_id', models.CharField(blank=True, db_column='RequesterID', max_length=15, null=True)),
                ('requester_role', models.CharField(db_column='RequesterRole', max_length=7)),
                ('isapproved', models.CharField(db_column='isApproved', max_length=1)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_request',
                'managed': False,
            },
        ),
    ]
